### ISSUE TITLE
Pymake fails to install if numpy isn't being installed manually first

### ISSUE THREAD

**Issue by Hofer-Julian** [modflowpy/pymake#111]
I get the following error message (I wonder why autotest pops up here at all):

```
Collecting mfpymake
  Using cached mfpymake-1.2.4.tar.gz (75 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Traceback (most recent call last):
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\config.py", line 419, in _parse_attr
          return getattr(StaticModule(module_name), attr_name)
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\config.py", line 26, in __init__
          spec = importlib.util.find_spec(name)
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\importlib\util.py", line 94, in find_spec
          parent = __import__(parent_name, fromlist=['__path__'])
        File "C:\Users\hofer_jn\AppData\Local\Temp\pip-install-ivzcy3zu\mfpymake_a60fcc056ca94562ba05233ab202b5e5\pymake\__init__.py", line 9, in <module>
          from .autotest.autotest import (
        File "C:\Users\hofer_jn\AppData\Local\Temp\pip-install-ivzcy3zu\mfpymake_a60fcc056ca94562ba05233ab202b5e5\pymake\autotest\autotest.py", line 54, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hofer_jn\AppData\Local\Temp\pip-install-ivzcy3zu\mfpymake_a60fcc056ca94562ba05233ab202b5e5\setup.py", line 3, in <module>
          setup()
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\_distutils\core.py", line 122, in setup
          dist.parse_config_files()
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\dist.py", line 818, in parse_config_files
          parse_configuration(
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\config.py", line 158, in parse_configuration
          meta.parse()
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\config.py", line 498, in parse
          section_parser_method(section_options)
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\config.py", line 469, in parse_section
          self[name] = value
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\config.py", line 222, in __setitem__
          value = parser(value)
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\config.py", line 599, in _parse_version
          version = self._parse_attr(value, self.package_dir)
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\site-packages\setuptools\config.py", line 422, in _parse_attr
          module = importlib.import_module(module_name)
        File "C:\Users\hofer_jn\Anaconda3\envs\xmipy\lib\importlib\__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "C:\Users\hofer_jn\AppData\Local\Temp\pip-install-ivzcy3zu\mfpymake_a60fcc056ca94562ba05233ab202b5e5\pymake\__init__.py", line 9, in <module>
          from .autotest.autotest import (
        File "C:\Users\hofer_jn\AppData\Local\Temp\pip-install-ivzcy3zu\mfpymake_a60fcc056ca94562ba05233ab202b5e5\pymake\autotest\autotest.py", line 54, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by jdhughes-usgs** [comment]
There is a numpy import at the top of autotest.py. However, I was able to install it in a clean environment on macOS. I have not tested this on other OSs.

```
(pymake_git) jdhughes@jdhughes-usgs-1918 Downloads % pip install mfpymake
Collecting mfpymake
  Downloading mfpymake-1.2.4.tar.gz (75 kB)
     |████████████████████████████████| 75 kB 1.7 MB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/jdhughes/opt/anaconda3/envs/pymake_git/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-install-urf5ks5z/mfpymake_d18005d852fa44aa843adb07e64ad691/setup.py'"'"'; __file__='"'"'/private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-install-urf5ks5z/mfpymake_d18005d852fa44aa843adb07e64ad691/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-pip-egg-info-n8wlq_ft
       cwd: /private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-install-urf5ks5z/mfpymake_d18005d852fa44aa843adb07e64ad691/
  Complete output (54 lines):
  Traceback (most recent call last):
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/config.py", line 419, in _parse_attr
      return getattr(StaticModule(module_name), attr_name)
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/config.py", line 26, in __init__
      spec = importlib.util.find_spec(name)
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/importlib/util.py", line 94, in find_spec
      parent = __import__(parent_name, fromlist=['__path__'])
    File "/private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-install-urf5ks5z/mfpymake_d18005d852fa44aa843adb07e64ad691/pymake/__init__.py", line 9, in <module>
      from .autotest.autotest import (
    File "/private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-install-urf5ks5z/mfpymake_d18005d852fa44aa843adb07e64ad691/pymake/autotest/autotest.py", line 54, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-install-urf5ks5z/mfpymake_d18005d852fa44aa843adb07e64ad691/setup.py", line 3, in <module>
      setup()
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/distutils/core.py", line 121, in setup
      dist.parse_config_files()
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/dist.py", line 798, in parse_config_files
      parse_configuration(
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/config.py", line 158, in parse_configuration
      meta.parse()
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/config.py", line 498, in parse
      section_parser_method(section_options)
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/config.py", line 469, in parse_section
      self[name] = value
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/config.py", line 222, in __setitem__
      value = parser(value)
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/config.py", line 599, in _parse_version
      version = self._parse_attr(value, self.package_dir)
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages/setuptools/config.py", line 422, in _parse_attr
      module = importlib.import_module(module_name)
    File "/Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 850, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "/private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-install-urf5ks5z/mfpymake_d18005d852fa44aa843adb07e64ad691/pymake/__init__.py", line 9, in <module>
      from .autotest.autotest import (
    File "/private/var/folders/78/gzs21ftn0fd24kx2lcqhmhgc0000gn/T/pip-install-urf5ks5z/mfpymake_d18005d852fa44aa843adb07e64ad691/pymake/autotest/autotest.py", line 54, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e8/ea/d1539f3e9422d10dbacaa5f4f85bc39248b553520d7cb349acf93225f16e/mfpymake-1.2.4.tar.gz#sha256=e45ec2b20e1444c798fb3e0bfd130a1bee01c7d423a76fb98c939dc01c584cdf (from https://pypi.org/simple/mfpymake/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mfpymake-1.2.3.tar.gz (69 kB)
     |████████████████████████████████| 69 kB 9.1 MB/s             
  Preparing metadata (setup.py) ... done
Collecting numpy>=1.15.0
  Downloading numpy-1.22.3-cp39-cp39-macosx_10_14_x86_64.whl (17.6 MB)
     |████████████████████████████████| 17.6 MB 7.7 MB/s            
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting networkx>=2.6.3
  Downloading networkx-2.7.1-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 39.3 MB/s            
Requirement already satisfied: idna<4,>=2.5 in /Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages (from requests->mfpymake) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages (from requests->mfpymake) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages (from requests->mfpymake) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/jdhughes/opt/anaconda3/envs/pymake_git/lib/python3.9/site-packages (from requests->mfpymake) (2.0.12)
Building wheels for collected packages: mfpymake
  Building wheel for mfpymake (setup.py) ... done
  Created wheel for mfpymake: filename=mfpymake-1.2.3-py3-none-any.whl size=67080 sha256=9ec114dddcd2410512b2cf92b0d13dae3f5e22e7bd5a901f4efc1d17070d07b6
  Stored in directory: /Users/jdhughes/Library/Caches/pip/wheels/7f/bc/bf/59da78335b8ec69fb544f3154a3e2462cf7d503f3c239ff9a1
Successfully built mfpymake
Installing collected packages: requests, numpy, networkx, mfpymake
Successfully installed mfpymake-1.2.3 networkx-2.7.1 numpy-1.22.3 requests-2.27.1
(pymake_git) jdhughes@jdhughes-usgs-1918 Downloads % 
```

**Comment by Hofer-Julian** [comment]
> However, I was able to install it in a clean environment on macOS

Interesting, so you got the error as well, but in the end it finished successfully?
I could imagine that excluding autotest similar to how it is done here would fix this: https://github.com/Deltares/xmipy/blob/91bcdb1077d7314119a1fa72871cc9a8db94fa39/setup.py#L55

**Comment by Hofer-Julian** [comment]
@jdhughes-usgs I see that you already work on a PR to fix this, thanks!
So just as another puzzle piece:
The problem is OS-independent as can be seen here: https://github.com/Deltares/xmipy/pull/71
One reason why it works for you might be that you installed pymake directly and not listed as a dependency as in my case.
